# Block 3: gm-rev-106 to gm-rev-160 (55 items)
# Products: 2318 (Cosmic Cat Brooch), 1820 (Lapis Lazuli), 2313 (Pisces Pet Collar), 2314 (Heart Harmony Pet Collar),
# and single SKU items 733 to 2165

BLOCK_3_REVIEWS = [
    # 1. Product 2318: "PRINCESS" Cosmic Cat Brooch (6 items: gm-rev-106 to gm-rev-111)
    ('gm-rev-106', 'Whimsical feline silhouette sculpted with fine jewelry finesse',
     'The micro-set gemstones forming the cosmic cat silhouette sparkle with charming subtlety on my winter wool lapel. The locking pin mechanism is secure and weighted nicely.'),
    ('gm-rev-107', 'A playful heirloom tribute to our beloved house companion',
     'The delicate curve of the cat tail and starry gemstone accents feel artful rather than kitschy. It adds a sophisticated personal touch to structured blazers.'),
    ('gm-rev-108', 'Impeccable metal finishing with vintage celestial details',
     'The warm gold tones complement the celestial motif. Arrived in a keepsake jewelry pouch that made unboxing feel special.'),
    ('gm-rev-109', 'Charming conversation starter at evening dinner gatherings',
     'Colleagues always lean in to admire the intricate starry pave settings. It holds its position securely on fine silk lapels without pulling threads.'),
    ('gm-rev-110', 'Sculptural elegance that honors the quiet grace of cats',
     'The proportions are balanced so the brooch sits flat against clothing without tilting forward. The gemstone setting work is crisp and refined.'),
    ('gm-rev-111', 'Delicate celestial craftsmanship with enduring emotional warmth',
     'A treasured gift that made my sister smile. The attention to micro-detailing across the ears and constellation accents is extraordinary.'),

    # 2. Product 1820: Elegant Lapis Lazuli and Clear Quartz Beaded Bracelet (5 items: gm-rev-112 to gm-rev-116)
    ('gm-rev-112', 'Deep ultramarine celestial blue flecked with golden pyrite stars',
     'Authentic Afghan lapis lazuli with rich natural royal blue saturation. The contrast against water-clear quartz spacers creates a crisp rhythmic elegance.'),
    ('gm-rev-113', 'A noble historical pigment translated into tactile wristwear',
     'Looking at the pyrite flecks in each lapis bead is like gazing into a starry midnight sky. The beads feel comfortably cool throughout the day.'),
    ('gm-rev-114', 'Refined contrast between nocturnal lapis and crystalline quartz',
     'The alternating pattern feels intentional and modern. The elastic has retained perfect tension through weeks of constant desk wear.'),
    ('gm-rev-115', 'Substantial lapis density with zero synthetic dye residue',
     'A simple wipe test confirms completely natural, un-dyed stone. The raw mineral character speaks for itself with dignified presence.'),
    ('gm-rev-116', 'Architectural mineral elegance that anchors creative focus',
     'Worn during studio work to foster steady mental clarity. The deep cobalt blue is striking against charcoal and linen shirts.'),

    # 3. Product 2313: The Pisces Guardian Pet Collar (4 items: gm-rev-117 to gm-rev-120)
    ('gm-rev-117', 'Gentle gemstone adornment crafted with pet comfort in mind',
     'Finding pet accessories that use authentic soothing stones without heavy hardware is rare. Our rescue cat barely noticed it on, and the aquamarine accents look lovely against her cream coat.'),
    ('gm-rev-118', 'Featherlight safety design with calming crystalline energy',
     'The breakaway safety closure works smoothly under gentle tension. The smooth tumble-polished stones sit flat and do not snag fine fur.'),
    ('gm-rev-119', 'Artisanal pet collar that feels like miniature wearable art',
     'The subtle sea-green and soft blue beads reflect serene oceanic calmness. Beautifully packaged with clear care guidelines for pet owners.'),
    ('gm-rev-120', 'A thoughtful protective charm for our beloved feline companion',
     'High quality stitching and smooth bead edges ensure complete safety. Our cat sleeps peacefully with it on, and it photographs gorgeously in morning window light.'),

    # 4. Product 2314: The Heart Harmony Pet Collar (4 items: gm-rev-121 to gm-rev-124)
    ('gm-rev-121', 'Soft rose quartz accents that bring gentle warmth to our puppy',
     'The blush pink quartz and calming jade beads are rounded to perfection with zero rough points. The leather strap is supple straight out of the box.'),
    ('gm-rev-122', 'Harmony of safety engineering and mindful mineral beauty',
     'Engineered with durable quick-release hardware so style never compromises safety. Our pup looks regal during our quiet park walks.'),
    ('gm-rev-123', 'Subtle romantic hues that celebrate our four-legged family member',
     'The dusty rose tones complement neutral fur tones effortlessly. Sturdy construction that withstands everyday puppy romping.'),
    ('gm-rev-124', 'Quiet luxury for discerning pet lovers who appreciate fine craft',
     'The tiny gemstone pendant adds just enough sparkle without clinking loudly against water bowls. Truly exceptional craftsmanship for pets.'),

    # 5. Single items: gm-rev-125 to gm-rev-160 (36 items)
    ('gm-rev-125', 'Warm terracotta jasper beads balanced with earthy sandalwood',
     'The rich brick red stones carry a grounding volcanic warmth, while the natural wood beads emit a faint soothing cedar scent upon skin contact.'),
    ('gm-rev-126', 'Serene sky blue turquoise paired with fragrant natural wood',
     'The robin egg blue stones feel smooth and calm against the wrist. An effortless everyday bracelet that feels connected to open western skies.'),
    ('gm-rev-127', 'Untamed quartz crystal termination suspended in rustic bronze',
     'The raw six-sided quartz termination has natural prismatic facets that catch room light like an unpolished prism. Authentic boho luxury.'),
    # 4-star constructive review
    ('gm-rev-128', 'Deep serene copper needles with subtle ambient lighting dependency',
     'The copper rutilated quartz is mesmerizing under direct sunlight where the metallic threads shimmer like liquid bronze. Indoors under dim evening light, the stone appears somewhat darker and more opaque than in the studio photos, but the internal geology is unmistakably authentic.'),
    ('gm-rev-129', 'Deep Bordeaux garnet tones complemented by brushed golden discs',
     'The wine-red beads glow like vintage port when held against the light. Sits flush against the wrist bone with satisfying mineral heft.'),
    ('gm-rev-130', 'Cool slate grey and denim blue beads for quiet coastal styling',
     'The matte stone finish gives this bracelet an organic pebble beach aesthetic. Very comfortable for typing and keyboard work.'),
    ('gm-rev-131', 'Miniature moss gardens preserved within crystal quartz spheres',
     'Looking into the green chlorite phantoms feels like inspecting fresh dew on mossy forest floors. Highly soothing during stressful days.'),
    ('gm-rev-132', 'Silvery aquamarine hues paired with lustrous grey freshwater pearls',
     'The muted platinum-grey aquamarine facets offer a modern, moody alternative to traditional pastel blue gems. Flawless silk draping.'),
    ('gm-rev-133', 'Complementary violet fluorite and forest jade tones in harmony',
     'The color blocking between purple and deep olive green feels fresh and painterly. Smooth spherical polish with zero surface imperfections.'),
    ('gm-rev-134', 'Soft creamy pastel aquamarine with comforting tactile roundness',
     'The milky seafoam beads remind me of summer gelato by the Mediterranean. Cool to the touch and uplifting to look down upon at work.'),
    ('gm-rev-135', 'Translucent prehnite inclusions interwoven with gentle amethyst',
     'The pale lime green prehnite exhibits lovely translucent depth, accented by soft lilac fluorite beads. Masterful color assembly.'),
    ('gm-rev-136', 'Ancient agarwood aroma paired with Tibetan lampwork glass',
     'The resinous warmth of authentic agarwood releases a subtle grounding fragrance throughout the day, while the patterned glass bead provides historical charm.'),
    ('gm-rev-137', 'Organic baroque pearl strand with soft romantic luster',
     'Each freshwater pearl possesses individual baroque asymmetry that feels sculptural rather than uniform. Drapes gracefully on bare skin.'),
    ('gm-rev-138', 'Deep royal purple amethyst punctuated by cobalt kyanite beads',
     'The rich violet beads contrast sharply with the bladed blue kyanite spacer. Sits securely without sliding excessively during movement.'),
    ('gm-rev-139', 'Delicate lilac quartz centered by a carved white jade blossom',
     'The floral center stone is carved with quiet precision, flanked by soft lavender quartz beads. A feminine heirloom design that feels timeless.'),
    ('gm-rev-140', 'Bold matte black onyx beads accented by micro-faceted golden pyrite',
     'The contrast between deep jet-black onyx and sparkling metallic pyrite rondelles is crisp and commanding. Excellent structural cord tension.'),
    ('gm-rev-141', 'Earthy coastal palette of celadon, mocha, and seafoam beads',
     'The natural landscape tones blend seamlessly with everyday linen and denim. Each bead has subtle natural veining that proves stone authenticity.'),
    ('gm-rev-142', 'Vibrant gemstone medley anchored by a sculpted equestrian charm',
     'The tiny brushed gold horse charm adds playful heritage character to the colorful gemstone strand. Elastic band is supple and strong.'),
    ('gm-rev-143', 'Organic peridot chips interwoven with polished moss agate',
     'The raw crystalline chip texture against the smooth round agate creates a pleasing sensory contrast when sliding the bracelet.'),
    ('gm-rev-144', 'Marbled sodalite and white howlite evoking ocean foam on dark cliffs',
     'Deep ink blue and snow-white mineral swirls make each bead a tiny abstract painting. Very pleasant weight and temperature retention.'),
    ('gm-rev-145', 'Verdant green aventurine paired with luminous button pearls',
     'The delicate green shimmer of aventurine compliments the creamy pearl nacre. Looks especially chic layered with a thin gold chain.'),
    ('gm-rev-146', 'Translucent lavender amethyst beads that cool tired wrists',
     'The uniform 8mm beads have excellent internal clarity with gentle lilac color zoning. Reassuring elastic tension that holds up well.'),
    ('gm-rev-147', 'Deep grape amethyst spheres with mirror-like hand polish',
     'Rich saturated purple tones that look royal under natural morning window light. Arrived in an embossed linen gift pouch.'),
    ('gm-rev-148', 'Convertible gemstone strand that shifts from choker to wrap bracelet',
     'The magnetic clasp allows seamless conversion between a delicate multi-strand wrap and a collar necklace. Ingenious functional jewelry.'),
    ('gm-rev-149', 'Nocturnal red pyrope garnets with sparkling quartz rondelles',
     'Deep pomegranate wine reflections emerge when illuminated from behind. Sits comfortably below watch straps without catching.'),
    ('gm-rev-150', 'Sun-drenched golden sunstone paired with crisp glacial aquamarine',
     'The copper platelet schiller in the sunstone flashes like golden confetti next to pale sky-blue aquamarine. A cheerful duo.'),
    ('gm-rev-151', 'Bicolor fluorite displaying zoned bands of rose and aubergine',
     'The natural fluorite color zoning looks like stained glass against the light. Brushed gold spacer beads add a warm frame.'),
    ('gm-rev-152', 'Smoky quartz grounding deepened by dark amethyst crystal beads',
     'The tea-colored transparency of the smoky quartz balances the violet amethyst beautifully. Sits flat on the wrist during typing.'),
    ('gm-rev-153', 'Vibrant emerald-tone chrome diopside with sparkling white zircon',
     'Intense grassy green saturation that rivals fine Colombian emeralds. The delicate micro-bead design feels light and feminine.'),
    ('gm-rev-154', 'Lustrous seed pearls interspersed with burgundy garnet beads',
     'Victorian romance re-imagined with modern clean lines. The crimson garnets provide rich warmth against the creamy pearl skin.'),
    ('gm-rev-155', 'Volcanic black obsidian paired with phantom quartz centerpiece',
     'The glossy black obsidian reflects mirror images while the central phantom bead houses an intricate green chlorite mountain.'),
    # 4-star constructive review
    ('gm-rev-156', 'Delightful artisanal necklace though tracking took two days to update',
     'The eclectic gemstone mix is wonderfully whimsical and high quality, with rich colors and great tactile weight. The carrier tracking number took over forty-eight hours to show initial movement after receiving dispatch confirmation, though delivery arrived within the estimated window once moving.'),
    ('gm-rev-157', 'Warm carnelian and sunstone hues with ornate vintage clasp',
     'The fiery sunset orange stones capture the lingering warmth of dusk. The filigree clasp has a secure double-latch safety mechanism.'),
    ('gm-rev-158', 'Electric mandarin spessartine accents beside cool aquamarine',
     'The contrast between vivid citrus orange and icy pastel blue is striking and youthful. Excellent lapidary polish on every bead.'),
    ('gm-rev-159', 'Water-clear rock crystal facets that refract brilliant rainbow prisms',
     'The micro-faceted quartz beads flash clear crystalline sparkles like miniature dewdrops on a cobweb. Elegant minimalist daily wear.'),
    ('gm-rev-160', 'Rare purple and violet labradorescence in a sculptural freeform stone',
     'Finding labradorite with violet-magenta flash rather than common yellow-green is extraordinarily rare. It sits majestically on my desk.')
]
