# Block 2: gm-rev-049 to gm-rev-105 (57 items)
# Products: 720, 727, 1550, 2119, 2223, 790, 799, 1546, 2066

BLOCK_2_REVIEWS = [
    # 1. Product 720: Faceted Purple Bead Bracelet (7 items: gm-rev-049 to gm-rev-055)
    ('gm-rev-049', 'Deep royal violet tones that catch soft morning light',
     'The micro-facets on each amethyst bead refract ambient light without being flashy. It rests lightly on the wrist, and the elastic core feels securely tensioned.'),
    ('gm-rev-050', 'Understated mineral clarity with subtle natural color banding',
     'The gradation across the purple beads reveals authentic quartz zoning. It pairs seamlessly with brushed sterling silver watch cases.'),
    ('gm-rev-051', 'Cool tactile weight that anchors afternoon focus at the desk',
     'Sliding the faceted beads between my fingers provides a soothing sensory break during demanding work sprints. The unboxing packaging was pristine.'),
    ('gm-rev-052', 'Subtle lilac to deep aubergine tones in natural sunlight',
     'In direct daylight the stones reveal crystalline violet depths while appearing discreetly charcoal-purple indoors. A wonderfully versatile daily piece.'),
    ('gm-rev-053', 'Smooth bead transitions with comfortable all-day wrist feel',
     'The polishing around the drill holes is clean with zero rough edges against the skin. Worn continuously for two weeks without stretching.'),
    ('gm-rev-054', 'Architectural facet cuts that elevate everyday knitwear',
     'The geometric faceting gives traditional purple quartz a crisp contemporary look. It looks refined peeking out from cashmere cuffs.'),
    ('gm-rev-055', 'A quiet gemological companion for daily mindfulness',
     'The stone beads carry a pleasant natural coolness when put on each morning. Exceptional presentation box and care documentation.'),

    # 2. Product 727: Multicolor Bead Bracelet (7 items: gm-rev-056 to gm-rev-062)
    ('gm-rev-056', 'Harmonious earthy color palette that avoids looking festive',
     'Curating multiple stones without clashing requires restraint. GlintMuse selected muted ochre, olive, dusty rose, and slate tones that blend into an organic landscape on the wrist.'),
    ('gm-rev-057', 'A subtle tapestry of genuine earth-mined mineral varieties',
     'Each bead represents a distinct geological formation. You can observe microscopic dendrites and mineral veils that confirm authentic raw provenance.'),
    ('gm-rev-058', 'Balanced weight distribution across diverse mineral densities',
     'Despite featuring varied gemstone species, the bracelet feels evenly weighted and drapes smoothly without twisting awkwardly.'),
    ('gm-rev-059', 'Earthy autumn hues that complement neutral linen wardrobes',
     'The subdued matte and semi-polished beads look bespoke rather than commercial. The dark linen pouch adds a thoughtful touch for travel.'),
    ('gm-rev-060', 'Tactile journey through varied natural stone textures',
     'Some beads have soft satin finishes while others have smooth crystalline lusters. Rotating them during phone calls is remarkably calming.'),
    ('gm-rev-061', 'Subtle conversation starter with organic tonal transitions',
     'Friends often notice the nuanced color story upon closer inspection. It feels cultured and artfully assembled.'),
    ('gm-rev-062', 'Durable stringing that maintains tension across daily wear',
     'I was hesitant about a multi-stone strand, but the internal cord has proven resilient through daily commuter wear and office resets.'),

    # 3. Product 1550: Moonlit Tanzanite Pearl Crystal Bracelet (7 items: gm-rev-063 to gm-rev-069)
    ('gm-rev-063', 'Ethereal periwinkle glow paired with luminous baroque orient',
     'The pleochroic shift of the tanzanite between cornflower blue and violet is breathtaking. Combined with freshwater pearls, it evokes twilight on calm water.'),
    ('gm-rev-064', 'Delicate wrist architecture with captivating color shifts',
     'The juxtaposition of icy tanzanite crystal and organic pearl luster feels poetic and timeless. It drapes delicately without catching on fine knitwear.'),
    ('gm-rev-065', 'A luminous evening piece with exceptional gemological character',
     'The natural baroque pearls have gentle iridescent overtones that amplify the cool lavender-blue facets of the tanzanite. The clasp is discrete and sturdy.'),
    ('gm-rev-066', 'Subtle twilight hues that flatter cooler skin undertones',
     'Tanzanite of this clarity is difficult to find in artisanal bracelets. It arrived packaged like high jewelry in an embossed cream box.'),
    ('gm-rev-067', 'Organic pearl contours softened by cool tanzanite facets',
     'The contrast between soft undulating pearl nacre and geometric gemstone faceting creates a compelling sculptural balance.'),
    ('gm-rev-068', 'Heirloom-grade craftsmanship with secure discrete closure',
     'Every knot is meticulously tightened. It feels featherlight yet substantial enough to be an anchor piece for milestone occasions.'),
    ('gm-rev-069', 'Dreamy celestial palette that transitions effortlessly to evening',
     'Under warm incandescent lighting the tanzanite displays violet-red flashes that complement the pearls. Truly an inspiring piece to wear.'),

    # 4. Product 2119: Wire-Wrapped Raw Citrine Pendant Necklace (6 items: gm-rev-070 to gm-rev-075)
    ('gm-rev-070', 'Golden amber warmth captured in architectural wire wrapping',
     'The raw citrine point retains its natural termination faces and honey-gold clarity. The delicate wire sculpture cradles the crystal securely without concealing its natural geometry.'),
    ('gm-rev-071', 'Raw crystal termination with vibrant internal sunlit phantoms',
     'Holding this pendant to the window reveals ethereal golden internal reflections. The tiny blue accent bead provides an unexpected painterly touch.'),
    ('gm-rev-072', 'Organic bohemian elegance refined for modern minimalist dress',
     'Unlike chunky wire jewelry, this wrapping is delicate and tailored. It rests right above the collarbone and adds sun-warmed energy to dark sweaters.'),
    ('gm-rev-073', 'Natural honey hues that prove unheated volcanic origins',
     'The pale Madeira tones avoid the harsh burnt orange of heat-treated quartz. It feels honest, organic, and grounded in earth history.'),
    # 4-star constructive review
    ('gm-rev-074', 'Beautiful raw crystal point with a wish for an extender link',
     'The raw citrine specimen has remarkable golden clarity and the wire wrapping is masterfully executed. My only minor note is that I would love an optional two-inch extender chain so I could wear it at mid-chest over thick winter turtlenecks.'),
    ('gm-rev-075', 'A ray of golden daylight suspended on the breastbone',
     'The raw crystal facets catch morning sun with radiant warmth. The packaging was immaculate and included a certificate of stone origin.'),

    # 5. Product 2223: Imperial Amethyst Geode on Wooden Stand (6 items: gm-rev-076 to gm-rev-081)
    ('gm-rev-076', 'Deep grape purple crystalline cave that commands quiet contemplation',
     'The color saturation is deep royal violet extending to the crystal tips. The custom wooden stand cradles the rough outer basalt base with museum precision.'),
    ('gm-rev-077', 'Substantial mineral presence that anchors the executive study',
     'Heavy, dark, and sparkling with natural quartz terminations. It sits next to my reading lamp and instantly grounds the ambient atmosphere.'),
    ('gm-rev-078', 'Undamaged crystal points and rich natural agate banding',
     'The transition from green celadonite skin through blue-grey chalcedony to crystalline purple amethyst is completely intact. Packed with immense care in heavy molded foam.'),
    ('gm-rev-079', 'Sculptural geological artifact with timeless natural aesthetics',
     'Having a raw slice of earth history in the living room creates a tranquil focal point. The crystals shimmer softly when room lights dim in the evening.'),
    ('gm-rev-080', 'Museum-worthy crystal density with deep royal saturation',
     'You can tell this was hand-selected rather than bulk-mined. The wooden stand has a warm matte walnut finish that complements the violet crystal cave.'),
    ('gm-rev-081', 'A contemplative centerpiece that transforms ambient desk space',
     'The crystalline cave absorbs and reflects room light with meditative subtlety. Friends and visitors always stop to examine its crystalline depth.'),

    # 6. Product 790: Premium Rutilated Quartz - Collector Grade (6 items: gm-rev-082 to gm-rev-087)
    ('gm-rev-082', 'Dense golden needle inclusions suspended in water-clear quartz',
     'The rutile needles form intricate crisscrossing networks like frozen celestial architecture. The clarity of the quartz matrix allows complete visual exploration from every angle.'),
    ('gm-rev-083', 'Collector-grade rutile density with exceptional internal transparency',
     'Under sunlight the golden titanium needles blaze with metallic luster. It feels heavy and cool, clearly a cut above typical retail grades.'),
    ('gm-rev-084', 'A miniature mineral cosmos encased in flawless polished spheres',
     'Each bead contains unique golden hair constellations. The bead stringing is tight and symmetrical, providing an empowering tactile presence.'),
    ('gm-rev-085', 'Metallic golden spears that reflect directional light brilliantly',
     'The contrast between the crystal-clear silica and the brassy golden needles is endlessly fascinating. A prized addition to my mineral collection.'),
    ('gm-rev-086', 'Refined masculine elegance with substantial mineral density',
     'Worn with tailored navy wool and watch cuffs. It delivers a discreet flash of gold without relying on ostentatious precious metals.'),
    ('gm-rev-087', 'Hypnotic golden straw inclusions that reward macro inspection',
     'Looking at the beads under a jeweler loupe reveals three-dimensional starburst patterns. Exceptional provenance and curation by the GlintMuse team.'),

    # 7. Product 799: White Howlite Bracelet - Calm Mind, Deep Sleep (6 items: gm-rev-088 to gm-rev-093)
    ('gm-rev-088', 'Silky porcelain white surface with delicate charcoal veining',
     'The gentle marble-like spiderweb veining gives each bead individuality without being chaotic. It feels cool against tired wrists at the end of the day.'),
    ('gm-rev-089', 'A cooling tactile anchor for evening wind-down rituals',
     'I wear this during bedtime meditation to slow down racing thoughts. The weight is soothing and the matte polish is soft like river stone.'),
    ('gm-rev-090', 'Minimalist monochromatic aesthetic that pairs with clean linen',
     'Crisp chalk-white tones with natural grey matrix lines. It stacks effortlessly with thin silver cuffs or wooden mala beads.'),
    ('gm-rev-091', 'Natural porous mineral coolness that eases physical tension',
     'Howlite has a unique dense thermal feel that stays cool longer than plastic or resin imitations. Unmistakably authentic stone.'),
    ('gm-rev-092', 'Gentle grey spiderweb matrix that proves earth-formed texture',
     'No two beads are alike, which I value deeply. The elastic band has remained taut through continuous wear and gentle washing.'),
    ('gm-rev-093', 'Serene bedside companion that encourages peaceful sleep habits',
     'Keeping this bracelet on the bedside nightstand has become a physical cue to disconnect from digital screens and breathe deeply.'),

    # 8. Product 1546: Pine Mist Green Phantom Quartz Bracelet (6 items: gm-rev-094 to gm-rev-099)
    ('gm-rev-094', 'Ghostly emerald triangular phantoms frozen inside mountain crystal',
     'The chlorite mineral layers form miniature pyramid mountains inside every single quartz bead. Looking into them is like staring into an alpine forest.'),
    ('gm-rev-095', 'Deep forest green mineral phantoms with crystalline clarity',
     'The green phantom steps illustrate centuries of geological growth pauses. A piece of profound meditative beauty that invites quiet reflection.'),
    ('gm-rev-096', 'An alpine sanctuary captured within clear silica spheres',
     'The mossy green inclusions have organic moss-like textures that contrast with the cold water-clear quartz. The presentation linen pouch was lovely.'),
    ('gm-rev-097', 'Subtle sage and pine hues that ground daily desk routines',
     'Whenever work feels overwhelming, looking down at these miniature green mountain silhouettes restores perspective. The bead sizing is uniform and comfortable.'),
    ('gm-rev-098', 'Remarkable growth chevron striations that celebrate geological time',
     'Finding phantom quartz where the internal chlorite caps are this well-defined is very rare. GlintMuse has exceptional lapidary sourcing.'),
    # 4-star constructive review
    ('gm-rev-099', 'Grounding alpine energy though outer packaging showed transit wear',
     'The phantom quartz beads are breathtaking with clear emerald pyramid tiers inside. The interior wooden jewelry box and velvet pouch were pristine, but the outer shipping carton had a slight crush on one corner from international transit. The bracelet itself is flawless and deeply loved.'),

    # 9. Product 2066: Blue Pietersite and Iridescent Labradorite Bracelet (6 items: gm-rev-100 to gm-rev-105)
    ('gm-rev-100', 'Nocturnal tempest swirling with midnight blue chatoyant silk',
     'Pietersite has this astonishing tempest-like chatoyancy that shifts as your wrist moves. Paired with peacock-blue labradorite flash, it looks like a stormy ocean.'),
    ('gm-rev-101', 'Electric blue flashes emerging from deep graphite darkness',
     'The labradorite displays vivid spectral schiller from multiple angles. It feels heavy, regal, and deeply grounding.'),
    ('gm-rev-102', 'Complex brecciated hawk-eye fibers with silky mineral luster',
     'The swirling breccia patterns in the pietersite resemble satellite views of cyclonic storms. Truly an intellectual, commanding piece of jewelry.'),
    ('gm-rev-103', 'Subdued executive style that reveals iridescent magic upon movement',
     'Under static indoor light it appears as a handsome dark stone bracelet, but under directional light the blues and golds ignite. Discreet and captivating.'),
    ('gm-rev-104', 'Deep indigo waves that reflect the mysteries of earth movement',
     'The combination of feldspar flash and amphibole chatoyancy showcases master-level lapidary selection. Fits comfortably without pinching arm hair.'),
    ('gm-rev-105', 'An enigmatic gemstone pairing with dramatic optical depth',
     'Wearing this feels like carrying the raw power of thunder and ocean spray on your wrist. Excellent craftsmanship and fast dispatch.'),
]
