# Block 4: gm-rev-161 to gm-rev-203 (43 items)
# Products: 2169 to 2306 and single SKU items 733 to 2067

BLOCK_4_REVIEWS = [
    # gm-rev-161 to gm-rev-172 (12 items)
    ('gm-rev-161', 'Versatile triple-wrap design in rich translucent tea tones',
     'The micro-faceted smoky quartz beads wrap three times around the wrist for a textured stacked look. Very light and easy to wear alongside a mechanical watch.'),
    ('gm-rev-162', 'Intricate Himalayan silver filigree framing golden rutile',
     'The handcrafted silver bezel has authentic antique patina, framing a clear quartz cabochon filled with bright golden needles. A museum-worthy talisman.'),
    ('gm-rev-163', 'Immaculately polished quartz showing distinct green chlorite pyramids',
     'The clarity of the quartz allows unobstructed viewing of the internal phantom mountain tiers. Smooth organic polish that feels serene in the palm.'),
    ('gm-rev-164', 'A miniature crystal planet showcasing deep violet geode hollows',
     'The polished sphere features a natural druzy pocket lined with sparkling purple crystal points. It rests on a turned wooden ring on my bookshelf.'),
    ('gm-rev-165', 'Ethereal pinkish-orange silky fibers suspended in clear quartz',
     'The fine rabbit hair rutile creates an ethereal gossamer cloud inside each bead. The colors look like a pastel sunset frozen in stone.'),
    ('gm-rev-166', 'Vibrant citrus feather inclusions dancing under direct light',
     'The vivid fanta orange plumes display remarkable feathered texture. One of the most uplifting and cheerful gemstone pieces in my daily rotation.'),
    ('gm-rev-167', 'Complex super seven mineral tapestry with kaleidoscopic inclusions',
     'You can spot lepidocrocite, cacoxenite, and smoky quartz zoning within the faceted rondelles. The depth of color shifts constantly as your hand moves.'),
    ('gm-rev-168', 'Harmonious trio of seafoam aquamarine, indigo kyanite, and dark rutile',
     'The contrasting mineral densities create a balanced grounding rhythm. Beautifully knotted on durable thread with a discrete brushed silver bead.'),
    ('gm-rev-169', 'Soft pastel rainbow fluorite complemented by emerald rutile drops',
     'The translucent mint and lavender fluorite cubes look like spun sugar, anchored by deep green rutilated quartz. Delightful artisanal balance.'),
    ('gm-rev-170', 'Fossilized amber flora encased beside crystalline mountain quartz',
     'The honey amber beads have delicate organic botanical flakes suspended from prehistoric forests. Warm, weightless, and deeply comforting against skin.'),
    ('gm-rev-171', 'Warm Baltic amber paired with royal amethyst for quiet balance',
     'The thermal warmth of ancient tree resin balances the icy crispness of amethyst crystal. A meaningful talisman worn during early morning meditation.'),
    ('gm-rev-172', 'Trio of smoky quartz, golden tiger eye, and needle rutile',
     'A strong, masculine combination of grounding earth tones. The chatoyant tiger eye banding rolls smoothly across the surface under lamp light.'),

    # gm-rev-173 to gm-rev-203 (31 items)
    ('gm-rev-173', 'Earthy red jasper beads paired with aromatic carved wood',
     'A second purchase for our household. The terracotta red jasper has a velvety smooth finish that pairs effortlessly with autumn knitwear and trench coats.'),
    ('gm-rev-174', 'Cool turquoise tones with natural grain wood spacers',
     'The sky blue hues carry an effortless western simplicity. The bracelet has comfortable stretch and does not bind during long laptop sessions.'),
    ('gm-rev-175', 'Raw unpolished crystal pendant with organic bronze bail',
     'I love jewelry that looks unearthed rather than mass manufactured. The crystal termination is completely natural and reflects morning light cleanly.'),
    ('gm-rev-176', 'Luminous copper threads shining through clean quartz matrix',
     'The copper needles have warm reddish-gold metallic luster. It arrived in an elegant green velvet pouch that makes safe storage effortless.'),
    ('gm-rev-177', 'Deep crimson garnet beads accented with brushed gold rondelles',
     'The garnet displays dark wine richness that becomes fiery under sunlight. Sits flush against the wrist bone with a tailored silhouette.'),
    ('gm-rev-178', 'Quiet indigo and stone-grey beads for minimalist everyday wear',
     'Muted tones that complement casual denim and navy blazers. The elastic cord has maintained resilience after months of continuous daily wear.'),
    ('gm-rev-179', 'Forest green chlorite phantoms encased in crystal clarity',
     'Looking at the miniature mossy pyramids brings immediate stillness during hectic workdays. The bead size is balanced and unobtrusive on the wrist.'),
    # 4-star constructive review
    ('gm-rev-180', 'Substantial tactile presence that softens after one week of wear',
     'The platinum-grey aquamarine and baroque pearls are exquisite, and the silver clasp is very secure. The knotted silk cord felt slightly stiff straight out of the presentation box, but after about a week of regular wear it draped beautifully against the skin.'),
    ('gm-rev-181', 'Harmonious violet amethyst and soft olive jade beads',
     'The muted complementary colors look like a botanical watercolor painting. Very smooth surface finish with zero rough spots around the drill holes.'),
    ('gm-rev-182', 'Pastel aquamarine beads with comforting rounded polish',
     'The pale seafoam tones look fresh and youthful. It feels light on the wrist and stacks well with my favorite silver wire bangle.'),
    ('gm-rev-183', 'Translucent prehnite and delicate lavender fluorite in harmony',
     'The soft apple green prehnite beads have an inner glow that pairs gently with the lilac stones. Arrived quickly and beautifully packaged.'),
    ('gm-rev-184', 'Subtle agarwood fragrance paired with historic Tibetan glass bead',
     'The natural wood beads warm up against body temperature and release a faint calming scent. A grounding piece for quiet mindfulness breaks.'),
    ('gm-rev-185', 'Asymmetrical baroque pearls with luminous cream and silver orient',
     'The organic contours of each pearl celebrate natural imperfection. It sits right at the hollow of the neck with graceful presence.'),
    ('gm-rev-186', 'Deep purple amethyst accented with crisp blue apatite facets',
     'The contrast between rich violet and vivid electric blue is striking yet tasteful. The bead stringing is tight, uniform, and comfortable.'),
    ('gm-rev-187', 'Soft lavender quartz centered by a delicate white lotus blossom',
     'A gentle heirloom piece that feels peaceful to wear. The carved central bead has crisp petal detailing and a silky matte finish.'),
    ('gm-rev-188', 'Matte black obsidian rondelles contrasted with brassy pyrite',
     'The modern monochromatic palette gives this bracelet a tailored edge. Looks great layered next to a leather watch strap.'),
    ('gm-rev-189', 'Muted earth and ocean tones in smooth tumbled river stones',
     'The dusty sage, terracotta, and denim hues blend into an organic landscape on the arm. Very soothing to rotate between fingers during meetings.'),
    ('gm-rev-190', 'Playful multicolor gemstone beads anchored by an equestrian charm',
     'The tiny golden horse charm adds subtle personal charm. The varied gemstone beads feel pleasantly cool upon first putting it on in the morning.'),
    ('gm-rev-191', 'Rough-cut peridot crystal chips paired with dark green jade',
     'The jagged raw peridot chips provide an energetic tactile contrast against the polished round beads. Exceptional artisanal craftsmanship.'),
    ('gm-rev-192', 'Swirling denim sodalite and snowy howlite with marble veining',
     'The oceanic color variations make every bead unique. It drapes naturally on the wrist without catching on fine sweater sleeves.'),
    ('gm-rev-193', 'Delicate seed pearls punctuated by vivid green emerald quartz',
     'The petite beads give this necklace an understated, vintage charm. It looks lovely layered under an open collar or summer dress.'),
    ('gm-rev-194', 'Clear lilac amethyst spheres with relaxing tactile smoothness',
     'The gentle purple beads have an internal glow that catches ambient office light. Durable cord that holds up through active daily routines.'),
    ('gm-rev-195', 'Deep aubergine amethyst with uniform hand-polished spheres',
     'Saturated purple tones that look luxurious and regal. The weight on the wrist is grounding without feeling cumbersome.'),
    ('gm-rev-196', 'Convertible gemstone strand offering flexible styling options',
     'I love being able to switch between a double-wrap bracelet and a graceful collar necklace. The magnetic closure holds firmly during wear.'),
    ('gm-rev-197', 'Rich wine garnets accented with micro-faceted smoky crystal',
     'The dark pomegranate hues look sophisticated and timeless. Beautifully balanced spacing between each gemstone rondelle.'),
    ('gm-rev-198', 'Glittering golden sunstone paired with pale glacial aquamarine',
     'The internal copper flecks in the sunstone sparkle like tiny stars beside the cool blue beads. A joyful, uplifting daily accessory.'),
    # 4-star constructive review
    ('gm-rev-199', 'Refined quiet luxury with delicate wrist sizing considerations',
     'The rose and grape fluorite beads have gorgeous translucent color zoning and the gold-tone spacers look sophisticated. The fit was slightly more tailored than expected, so I recommend measuring your wrist carefully against the size guide before ordering. Once on, it is stunning.'),
    ('gm-rev-200', 'Smoky quartz tea tones balanced with calming amethyst beads',
     'The translucent earth tones create an easy neutral palette that pairs with grey or camel wool coats. Sits comfortably against the wrist.'),
    ('gm-rev-201', 'Vibrant emerald green stones with delicate clear quartz spacers',
     'The saturated green catches eyes without being ostentatious. Packaged with care in a textured presentation box with a handwritten note.'),
    ('gm-rev-202', 'Lustrous ivory pearls and deep red garnet beads in harmony',
     'The contrast between soft organic pearl nacre and dark mineral garnet is timeless. A discreet heirloom piece that transitions from day to night.'),
    ('gm-rev-203', 'Glossy obsidian beads centered with a crisp phantom quartz sphere',
     'The midnight black stone is polished to a glass mirror finish, highlighting the miniature green chlorite garden within the center stone.')
]
